apiVersion: v1
kind: Service
metadata:
  name: {{ include "excalidraw.fullname" . }}-room
  labels:
    {{- include "excalidraw.room.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "excalidraw.room.selectorLabels" . | nindent 4 }}
